#!/bin/bash

# Check if the version parameter is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <version>"
    exit 1
fi

# Get the version from the first parameter
VERSION="${1#v}"

# Create the version.py file
echo "# This file is automatically generated by update-version.sh" > l1nkzip/version.py
echo "VERSION_NUMBER = \"$VERSION\"" >> l1nkzip/version.py

# Update the version in pyproject.toml
sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml

echo "Version $VERSION has been written to l1nkzip/version.py and updated in pyproject.toml"
