name: ci
on: pull_request

jobs:
  cloud-all:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: test root
        run: |
          make test
        working-directory: .
