name: Deploy Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'user-guide/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: user-guide
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy documentation
        working-directory: user-guide
        run: |
          mkdocs gh-deploy --force
